### ISSUE TITLE
Columna que no existe en función `get_pipeline_report` 

### ISSUE THREAD

**Issue by pa00gz** [ixpantia/lacrmr#9]
Me tira un error al usar esa misma función `get_pipeline_report` porque me dice que la columna `result_email` no existe. Eso supongo que es ya algo a nivel de la función que cambió el nombre en algún lado o algo por el estilo.

**Comment by ronnyhdez** [comment]
Error se da no porque la columna no exista. Se debe a que el uso del tryCatch y el manejo del error no es adecuado.

Si api no trae respuesta, no tiene datos y error se da hasta el momento en que decimos que queremos hacer una columna en un conjunto de datos no existente.
